# -*- coding: utf-8 -*-
"""Minu Choi DS - Number Guess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thbcKW4v_1aCr8-xUWEijEB4fW8-G3VJ
"""

!pip install numpy

import numpy as np

def guess_random_number():
    random_number = np.random.randint(0, 100)
    number_of_guesses = 0

    while True:
        user_guess = input("Guess a number between 0 and 100:")

        try:
            user_guess = int(user_guess)

            if user_guess < 0 or user_guess > 100:
                print("Enter a number between 0 and 100.")
                continue

            number_of_guesses += 1

            if user_guess == random_number:
                print(f"You got it! It was {random_number}.")
                print(f"It took you {number_of_guesses} guesses!")
                break

            elif user_guess < random_number:
                print("Too low!")

            else:
                print("Too high!")

        except ValueError:
            print("Enter a valid integer.")

guess_random_number()

"""As shown above when the user enters a number less than 0, it returns "Enter a number between 0 and 100." The same occurs when the user enters a number greater than 100. When the user enters a float, it returns "Enter a valid integer." In any case, the game does not stop; it continues until the user enters a valid integer between 0 and 100.


When the user correctly guesses the random number, it returns "You Got it!" In addition, it displays the random number alongn with the number of guesses taken by the user.
"""
